### ISSUE TITLE
챌린지 API 인가 로직 추가

### ISSUE THREAD

**Issue by alscksdlek** [2-Docthru-team1/2-Docthru-team1-BE#118]
## 작업 사항 설명
챌린지 API 인가 로직 추가

## TO-DO
- [x] 로그인한 유저만 챌린지 생성(신청) 가능
- [x] 챌린지 정보 수정시 requestUserId와 챌린지를 수정을 요청한 사람의 id 확인
- [x] 챌린지 상태 수정은 수정을 요청한 사람의 role이 admin인지 확인
