### ISSUE TITLE
challenge 이미지 처리

### ISSUE THREAD

**Issue by alscksdlek** [2-Docthru-team1/2-Docthru-team1-BE#124]
## 작업 사항 설명
challenge 이미지 처리

## TO-DO
- [x] post 요청 업로드 URL 생성 로직 추가
- [x] get 요청 다운로드 URL 생성 로직 추가
- [x] patch 요청 업로드 URL 생성 로직 추가
