### ISSUE TITLE
회원가입 구현

### ISSUE THREAD

**Issue by csbizz** [2-Docthru-team1/2-Docthru-team1-BE#13]
## 작업 사항 설명

회원가입 기능을 구현한다

## TO-DO

- [x] 비밀번호를 해시하는 미들웨어 작성
- [x] 변경된 유저 스키마와 비밀번호 해싱에 맞는 스키마로 유저 모델 수정
- [x] 새 스키마로 마이그레이션
- [x] 형식 오류를 검증하기 위한 에러 핸들러 작성
- [x] 변경된 스키마에 맞게 타입스크립트의 유저 인터페이스, 유저DTO 수정
- [x] 유저 형식 검증을 위해 superstruct 객체 작성
- [x] 프론트엔드 통신이 가능하도록 미들웨어 설정

## 기타
