### ISSUE TITLE
챌린지 GET API 변경

### ISSUE THREAD

**Issue by taeyeonkim94** [2-Docthru-team1/2-Docthru-team1-BE#149]
## 작업 사항 설명
프론트측 요구사항으로 추가된 옵션 적용
## TO-DO

- [ ] 챌린지 좋아요 정렬추가
- [x] 챌린지의 participants 참여자 시딩데이터에서 추가
- [x] 검색키워드 범위 타이틀로 변경
- [x] 검색 대소문자 구분 추가
- [x] 미디어타입 여러개 선택할 수 있게 변경
