### ISSUE TITLE
리스폰스 수정

### ISSUE THREAD

**Issue by taeyeonkim94** [2-Docthru-team1/2-Docthru-team1-BE#165]
## 작업 사항 설명
챌린지 목록 조회 리스폰스 수정,
워크 목록 조회 리스폰스 수정,
워크 상세 조회 리스폰스 수정,
워크 삭제 리스폰스 수정
그 외 userId를 무분별하게 사용한 곳 수정
## TO-DO
- [ ] 챌린지 목록 조회 리스폰스 수정
- [ ] 워크 목록 조회 리스폰스 수정
- [ ] 워크 상세 조회 리스폰스 수정
- [ ] 워크 삭제 리스폰스 수정
- [ ] userId를 무분별하게 사용한 곳 수정
