### ISSUE TITLE
챌린지 스키마 필드 추가

### ISSUE THREAD

**Issue by alscksdlek** [2-Docthru-team1/2-Docthru-team1-BE#177]
## 작업 사항 설명
챌린지 스키마 필드 추가

## TO-DO
- [x] 스키마 필드 monthly추가
- [x] 스키마 필드 number추가
- [x] 마이그레이션
- [x] 시드 실행 확인
