### ISSUE TITLE
challenge 목록 조회 api 구현

### ISSUE THREAD

**Issue by taeyeonkim94** [2-Docthru-team1/2-Docthru-team1-BE#23]
## 작업 사항 설명
challenge 목록 조회 api 구현

## TO-DO
- [x] page에 맞춰서 나오게 구현
- [x] pageSize에 맞춰서 나오게 구현
- [x] 정렬에 따라 나오게 구현
- [x] keyword로 검색할 수 있게 구현
## 추가 작업 사항
- [x] keyword 값이 안받아와지는 버그 수정
- [x] 생성되어있던 pagination.validation의 에러 메시지를 영어에서 한글로 변경
- [x] jwt의 sign 메소드 호출 방식에서 생긴 에러 수정
## 기타
