### ISSUE TITLE
이달의 랭커 api 구현

### ISSUE THREAD

**Issue by taeyeonkim94** [2-Docthru-team1/2-Docthru-team1-BE#251]
## 작업 사항 설명
이달의 랭커 api 구현
## TO-DO
- [x] 이달의 랭커 api구현
- [x] 좋아요 모델 추가
- [x] 구현 되어 있던 좋아요 api 수정
