### ISSUE TITLE
challenge, recipe 이외의 타입 계층 구조 정리

### ISSUE THREAD

**Issue by csbizz** [2-Docthru-team1/2-Docthru-team1-BE#34]
## 작업 사항 설명

이미 작업 중인 두 모델 제외한 모델들을 새로 수정된 스키마에 맞도록 계층 구조 변경

## TO-DO

- [x] 각 계층을 Prisma 기준으로 변경
- [x] types에 재정의했던 타입들을 Prisma/client의 타입으로 변경
- [x] repository의 생성자 형식 통일

## 기타
