### ISSUE TITLE
챌린지 작업물 조회 구현

### ISSUE THREAD

**Issue by taeyeonkim94** [2-Docthru-team1/2-Docthru-team1-BE#82]
## 작업 사항 설명
챌린지 작업물 조회 구현
## TO-DO
- [x] 챌린지 작업물의 id를 이용한 api 구현
- [x] 챌린지 작업물의 리스트를 조회하는 api 구현
- [x] 테스트에 필요한 목데이터 추가
